### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pheldox** [khitk9738/EyeVis#2]
Please is there any documentation on the app so that one can be able to make changes with ease. I am very interested in how the application detect approaching vehicles or obstacles.

**Comment by khitk9738** [comment]
Few lines from the project report: -
Moving vehicles are a source of greatest danger to a person so, in case of
detection of vehicles class the current matrix is sent to comparison with the
cached matrices in order to calculate the number of boxes occupied by the
object based on YOLO of the 13x13 boxes generated for YOLO. This helps in
identifying whether the vehicle is approaching or receding upon comparison
between the number of boxes occupied among different frames.
The results are then appended onto the frame and displayed in the Cam-
era Activity. Single tap in this activity calls the Text to Speech handler to
speak out the names of classes present in a particular frame.
